#!/bin/bash
java -classpath /Applications/Mathematica.app/Contents/SystemFiles/Links/JLink/JLink.jar -jar ~/Projects/MAT4951/out/artifacts/src_jar/src.jar -genPackage "" -genPackageArguments package_args -genKernelArguments "-linkmode launch -linkname"  -genKernel "/Applications/Mathematica.app/Contents/MacOS/MathKernel" -minKernel "/Applications/Mathematica" -minKernelArguments ""


